### ISSUE TITLE
Java - Manual Instrumentation - What is an Event?

### ISSUE THREAD

**Issue by algattik** [open-telemetry/opentelemetry.io#1032]
https://opentelemetry.io/docs/instrumentation/java/manual_instrumentation/#create-spans-with-events states:

_Spans can be annotated with named events that can carry zero or more Span Attributes, each of which is itself a key:value map paired automatically with a timestamp._

https://opentelemetry.io/docs/concepts/glossary/ states:

_Event: Something that happened where representation depends on the Data Source. For example, Spans._

This is contradictory and not clear. Should we assume that an Event is really a span of zero duration?

**Comment by cartermp** [comment]
There is a broader gap here that we'll need to solve: there is very little conceptual documentation about each of these concepts.

Ideally, we have a document or part of a document describe what span events are, what they're good for, and when you might generally use them. Then each language's manual instrumentation docs link to that doc or section, then simply document how you create one in that language.

...then repeat that for every major tracing (and soon metrics!) concept 🙂 

Interested in contributing? Happy to review anything you've got!

**Comment by cartermp** [comment]
We now have a language-agnost conceptual doc that explains what span events are here: https://opentelemetry.io/docs/concepts/signals/traces/#span-events

I've been (slowly...) working through instrumentation pages and adding links to this and other concepts. .NET and JS have these links. I'll close this out since the concept is documented, and in time it will also be linked to from all the languages.
