### ISSUE TITLE
Node.JS

### ISSUE THREAD

**Issue by enyinna1234** [open-telemetry/opentelemetry.io#1114]
The documentation here does not make it clear how to use the exporters or tracing backends with the tracing.js provided. For instance how does one add a specific backend code to the tracing.js file?

**Comment by cartermp** [comment]
@enyinna1234 There's a page about exporters here - exporters are how you get data to a particular place: https://opentelemetry.io/docs/instrumentation/js/exporters/#otlp-endpoint-or-collector

Would it be helpful to have a code comment and a link to this page in the code sample so that it's clearer where the exporter goes?

**Comment by chalin** [comment]
@enyinna1234 - I'll assume that you're satisfied with @cartermp's response. If not, feel free to reopen this issue.
