### ISSUE TITLE
OTel Tuesday Page/Info

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#1168]
things to decide:
- Otel Tuesday 'what is it' page
- Links to archives
- Stream to YouTube/archive to YouTube
- Topic/guest suggestions

??

**Comment by henrikrexed** [comment]
We should share the regular updates on the project. 
Where to find the latest stable version of the library.

Explain the different type of Sampler, SpanProcessor ....Etc.

**Comment by nemerkab** [comment]
Regarding the topic/guest list: There are 20 streams remaining in 2022.
I suggest we aim for 10 guests so half of the streams have a guest and half are the current format. That will allow us to compare engagement between the 2 formats to see which is better received. If the guest format is clearly winning then we can move to have a guest every episode.

Here are possible topics that we could discuss. We could seek contributors from the community to speak on each topic.

Traces - what's new, why it matters
Metrics - what's new, why it matters
Logs - what's new, why it matters
Specification - what's new, why it matters
End user story - tell us about your journey with OpenTelemetry at your company
Traces - what's new, why it matters
Metrics - what's new, why it matters
Logs - what's new, why it matters
Specification - what's new, why it matters
End user story - tell us about your journey with OpenTelemetry at your company

Keeping with the current stream schedule, that is 1 topic/guest a month. There would be 6 months between topic repeats which is plenty of time for exciting changes to develop in those areas. We would still announce changes as they occur in the alternating streams, but we would dive deeper into the specific areas on those stream dates. 

I kept the topics pretty high level to capture a wider audience and make it easier to find guests. If feedback from the audience says we should go into more specific topics/components of OpenTelemetry then we could change the topics to align with the feedback.  The more specific we get with topics, the more we need to think about architecting the stream for on demand viewing instead of live viewing.

**Comment by austinlparker** [comment]
I think creating a page/section for it is probably off the books for now, but I don't want to just dumpster the whole thing in case someone else wants to come in and start running it, y'know?

**Comment by cartermp** [comment]
@austinlparker is otel tuesday still happening?

**Comment by cartermp** [comment]
I...think we can probably close this for now. Can always re-open but if the program isn't being picked up any time soon then I don't think it's worth tracking.
