### ISSUE TITLE
Document when you'd want to use a collector

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry.io#1214]
This is probably worth putting in collector conceptual docs, and linked to from some other places.

In my company's community slack, we got a fantastic question:

> not sure which channel this goes into, so starting here: under what circumstances does one use a collector to send OpenTelemetry traces, as opposed to having each service send direct to Honeycomb?

This is definitely a general question/concern and not specific to one vendor. Some answers in the thread given were:

* Wanting to process all spans prior to sending to a backend
* Wanting to hook up to other sources (e.g., OpenTracing traces)
* Wanting to have all of your export concerns live in a single place (e.g., sending data to several sources)
* you want to manage your API keys and destination dataset in a central place (or, are separating that configuration concern from application code and config)
* you want or need a central point of egress (generally a security concern) This is sometimes referred to as the "collector gateway" pattern

What other scenarios are worth documenting?

This could also fall under a general "guidance and best practices" bucket that OTel has basically no docs for. Maybe the collector is a great place to kick off such kinds of docs!

**Comment by svrnm** [comment]
While I agree that this is an important question, I would make "not using a collector" the exception rather the norm, so instead of asking "under what circumstances does one use a collector", the question is "under what circumstances does one not use a collector" and the only answer to that (*in my opinion*) is in a small scale environment or in a pre-production environment. A few pointers why I think that way from the  [docs](https://opentelemetry.io/docs/collector/getting-started/):

> In addition, the Agent can offload responsibilities that client instrumentation would otherwise need to handle including batching, retry, encryption, compression and more. OpenTelemetry instrumentation libraries by default export their data assuming a locally running Collector is available.

If you look at things that way, you don't need to implement a vendor (e.g. honeycomb) specific exporter in each and every language, just use OTLP, send it to the collector, transform it to whatever you need in the backend there. Less code to maintain, more contribution to other areas of the language-specific SDKs.

Also, the likelihood that you will need some additional handling (batching, retry, encryption, compression, PII filtering) sooner than later in a production environment is high.

> A Gateway cluster runs as a standalone service and can offer advanced capabilities over the Agent including tail-based sampling. In addition, a Gateway cluster can limit the number of egress points required to send data as well as consolidate API token management. 

This agrees with what you said: It's first of all a security improvement (less points of egress, less points that own credentials), but also yet another simplification for the language-specific SDKs, since their is no need to maintain all the authentication code there (especially, if you think about more advanced mechanisms like Oauth).

**Comment by austinlparker** [comment]
It seems to me that there's broad alignment around "collector-as-default" deployment models for OpenTelemetry, especially given that the default OTLP exporters in each language assume a local collector endpoint. I think this also holds into the future as OpenTelemetry is integrated into more libraries/frameworks -- you'd start up a collector and you'd just start getting telemetry.

**Comment by cartermp** [comment]
Hmmm, I don't know if there's necessarily broad alignment in user expectations. Smaller-scale and pre-production are quite valid scenarios. I agree that you should eventually be using a collector, even for smaller-scale things when in production. But that's just not spelled out anywhere. Motivating examples might help for developers who aren't as savvy towards production concerns like this, or just get general anxiety over "opsy" stuff like standing up a collector proxy.

**Comment by cartermp** [comment]
I feel like a "Why use the collector?" article could fit nicely under https://opentelemetry.io/docs/collector/ as well. Might not be terribly long, but listing off several motivating scenarios and then linking to it in lots of places could be nice. I think that the collector docs in general should also be linked to in every exporter page we have in languages, perhaps under Next Steps.
