### ISSUE TITLE
auto-instrumentation for Java Spring Kafka Streams - is NOT generating the Jaeger Deep Dependency graph with Producer and Cosnumer

### ISSUE THREAD

**Issue by dharmaplay** [open-telemetry/opentelemetry.io#1231]
Hi,
I have written 1 Producer and 1 Consumer using Spring Kafka streams/Cloud streams and able to see the traces in JaegerUI but when I click on the Deep Dependency graph its not showing the graph like

Producer --> Kafka TopicName --> Consumer.

Is it possible to generate Information above like Producer ->TopicName -> Consumer informations like traces and metrics?

Thanks
Dharma

**Comment by chalin** [comment]
This repo is for the OpenTelemetry website. You should direct your question to a more appropriate forum. For example, see the links to **discussions** or **mailing lists** under the [Community > Communication](https://github.com/open-telemetry/community#communication).

Since you aren't reporting a problem with the website, I'll close this issue.
