### ISSUE TITLE
.NET has a local Getting-started page and an external reference

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1320]
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry.io/pull/1319#discussion_r859032031_

> All: I have a question unrelated to the changes in this PR, but relevant to this page. Given that this section of the website (i.e., .NET instrumentation) has a [Getting started page](https://opentelemetry.io/docs/instrumentation/net/getting-started/), can we drop the **Getting Started** entry below (lines 35-36)?

- [x] #1364

**Comment by chalin** [comment]
@reyang wrote:

> I can see the problem here - the [getting started page](https://opentelemetry.io/docs/instrumentation/net/getting-started/) is only talking about traces, it does not cover logs and metrics. And the doc wasn't reviewed by any .NET approver/maintainer.

So I believe that you're suggesting that the (site-local) **Getting started** page be updated? If so, @cartermp is this something that you have time for?

**Comment by reyang** [comment]
> So I believe that you're suggesting that the (site-local) Getting started page be updated? If so, @cartermp is this something that you have time for?

Yes. And moving forward we might need some systematic way of keeping these docs up-to-date.

Couple things to consider:
* Do we require language maintainers/approvers to review/approve the change for each language?
* Do we expect the maintainers to keep the content fresh here once they release new versions of packages?
* Do we want to have contents in both places (language repo and here) or it should be one single place?

**Comment by cartermp** [comment]
Happy to add sections for metrics and logs - it's pretty simple to add - Some additional thoughts:

We don't have a precedent for how to recommend which signal to start with. I believe traces are the best signal to use to diagnose a system, and new users should start there. This is the _de facto_ guidance anyways for the most part, since metrics and logs are not as mature as tracing across all of OpenTelemetry. But it's something we're going to want to think about outside the scope of .NET docs, perhaps with .NET docs leading the charge on how to actually organize this content.

As for these questions, here's my opinion:

> Do we require language maintainers/approvers to review/approve the change for each language?

We should definitely set up .NET approvers as a code owner for the .NET docs here. We do this for other languages too, so it's easy to do on this repo's side.

The biggest question then is if any changes should _require_ a .NET approver to actually merge. This hasn't been a problem in other languages so far, but I anticipate at some point that PRs could linger if we do require this, and if required approvers don't have the time to look over docs changes as well, we could hold things up unnecessarily.

> Do we expect the maintainers to keep the content fresh here once they release new versions of packages?

That would be *amazing*, yes, but with one caveat: probably only for things that are stable. This may not be a .NET docs concern, but if a concept is backed by a preview component that's likely to get breaking changes moving forward, then the concept might not be worth documenting yet. I wouldn't want maintainers to have to update docs for things that are probably going to change a lot anyways.

But in this case (e.g., logs land with a stable integration with ILogger), then any updates would be highly appreciated. And we can of course work to massage the content into the right format over time 🙂 

> Do we want to have contents in both places (language repo and here) or it should be one single place?

I'd say that can be up to language repo maintainers. I would personally prefer to migrate stuff out of the language repo to here, with perhaps a backlink in a doc where content used to reside. I've found that Google and other search engines rank the opentelemetry site higher for most queries, so centralizing docs here is likely best. But I'd defer this to language repo owners.

**Comment by reyang** [comment]
> We don't have a precedent for how to recommend which signal to start with. I believe traces are the best signal to use to diagnose a system, and new users should start there. This is the de facto guidance anyways for the most part, since metrics and logs are not as mature as tracing across all of OpenTelemetry. But it's something we're going to want to think about outside the scope of .NET docs, perhaps with .NET docs leading the charge on how to actually organize this content.

In .NET we started with trace 2 years back, now we've tweaked it by giving people options regarding which signal (logs/metrics/traces) they want to get started with - https://github.com/open-telemetry/opentelemetry-dotnet#getting-started

**Comment by austinlparker** [comment]
Some thoughts --

- Re: Approvers, we can add .net maintainers as code owners to the docs path. @chalin or @cartermp?
- In general, I'd prefer OpenTelemetry website docs to be trace-first. .NET is extremely far out in front of the rest of the project in terms of log support and the majority of OpenTelemetry users are coming in for tracing. I would rather not cause frission with end-users asking why .NET is so different than the rest of the languages by having a completely unique experience with their docs on the site. 
- To echo @cartermp, stable docs should live here. They can be a mirror of what you have in your repo, but we're trying to make the opentelemetry.io domain authoritative for opentelemetry documentation. 

If you'd like to discuss this more @reyang feel free to reach out to us on slack in #otel-comms

**Comment by chalin** [comment]
I'm going to close this since the "Getting Started entry [at] (lines 35-36)" is gone, and that was the original topic of this issue. In the interim, we resolved #1364 too.

Feel free to reopen if y'all think that there's more to do that is in scope.
