### ISSUE TITLE
Python exporters docs omit the default traces/metrics access path

### ISSUE THREAD

**Issue by pilhuhn** [open-telemetry/opentelemetry.io#1586]
**What needs to be changed?**

https://opentelemetry.io/docs/instrumentation/python/exporters/#trace-1 mentions for exporting traces the OTLPSpanExporter with its endpoint, but does not mention that the user has to supply the `/v1/traces` path if the endpoint is passed in code. 
Same applies to the env variable `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` 
If the endpoint is passed via Env variable `OTEL_EXPORTER_OTLP_ENDPOINT` is used, then the exporter code appends the `/v1/traces` (seems http exporter only)

Make it obvious that the endpoint may need the path parameter `/v1/traces` and/or the user should consult the documentation of the collector used. I guess though that `/v1/traces` is pretty much a standard.

**Comment by cartermp** [comment]
Great catch!

**Comment by cartermp** [comment]
Hmmm, actually, this is always kind of confusing since the main thing shown here is gRPC.

> If the endpoint is passed via Env variable OTEL_EXPORTER_OTLP_ENDPOINT is used, then the exporter code appends the /v1/traces (seems http exporter only)

My understanding is that this is not necessary for gRPC. I do not believe that `/v1/traces` or `/v1/metrics` are required for gRPC export.

There's a separate subsection that talks about using HTTP. Here is where the info would most likely need to go.
