### ISSUE TITLE
Create a back up domain name

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry.io#16]
See discussion here: https://github.com/open-telemetry/opentelemetry.io/issues/15

We can discuss alternatives:

- dev
- net
- org
- com

I think `dev` is cool, but project is not only about developers. So maybe `org` would be nicer.

**Comment by iredelmeier** [comment]
Definitely.

It's probably worth grabbing those alternatives (e.g., variations on both `opentelemetry` and `open-telemetry`, as well as on TLDs) that are both available and not ridiculously expensive, so that squatters and other malicious parties can't cause future sadness.

(My super quick, incomplete search suggests that `open-telemetry` is available for $12 with most major TLDs, but `opentelemetry` is... not.)

**Comment by caniszczyk** [comment]
we have opentelemetry.dev already, if there is a list of domains you want the LF/CNCF to pick up, let us know

**Comment by SergeyKanzhelev** [comment]
I personally fine with opentelemetry.dev. @iredelmeier I looked - those are all premium domains. I don't really see a value in preventing squatting. Let's close the issue. 

/all - please reopen if you believe we need more than `.dev ` as a back up.
