### ISSUE TITLE
Baggage content is too trace related, .NET specific example is confusing

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry.io#1878]
Couple suggestions:
1. The contents are too trace related. Baggage can be used for all signals, not just as span attributes. Metrics can have attributes populated from baggage. Same with logs
2. I'd recommend to use a diff. example as `Activity.Current?.SetTag("AccountId", accountId)` is .NET specific, which can confuse users as .NET calls its spans "Activity". Users will find it confusing. If we keep the same example, mention in code comment that Activity is .NET's representation of Span.

**Comment by cartermp** [comment]
Agreed overall, although I'd say that Baggage is currently the _most_ useful in tracing since it lets you propagate metadata along the rest of a trace, whereas this kind of capability is less important outside the context of tracing. So while it's true that it's independent from tracing, it's also much more niche to consider it outside the context of tracing, since going through the pains of propagating baggage without getting the benefit of tracing is kinda weird.

**Comment by theletterf** [comment]
@cijothomas Are you up for it? :)

**Comment by cijothomas** [comment]
> @cijothomas Are you up for it? :)

I'll help review any PRs addressing this. I just don't have the bandwidth to work on an actual PR itself.

**Comment by cartermp** [comment]
Closing as per doc update
