### ISSUE TITLE
Add a documentation page for all integrations with multiple language support

### ISSUE THREAD

**Issue by Bhargavamacha** [open-telemetry/opentelemetry.io#237]
Discussion @ #44, Continued here.

**Comment by ffe4** [comment]
Could you clarify what you want to discuss in this issue? #44 was specifically for Jaeger and discussion could be continued there. If you want merge this with the Prometheus #45 discussion, since you want to work on both issues anyway, the title should probably be about exporter configuration. Or do you want to talk more generally about how to implement docs for multiple languages for #203 ?

**Comment by Bhargavamacha** [comment]
The issue's for implementing docs for multiple languages for #203.

**Comment by cartermp** [comment]
I'll close this out since it's more or less done in many languages - with respect to exporters, which the original issue was about. The pattern is that each language has an Exporters doc, and there we list console/otlp/jaeger/zipkin/prometheus, all depending on which SDK has which kind of exporter. So it's sort of the inverse. Instead of $EXPORTER page that then lists all the languages, the language exporter pages list each $EXPORTER.
