### ISSUE TITLE
Python docs incorrectly use `__name__` for `instrumenting_module_name`

### ISSUE THREAD

**Issue by WesleyAC** [open-telemetry/opentelemetry.io#2517]
**What needs to be changed?**

The [docs for `trace.get_tracer`](https://opentelemetry-python.readthedocs.io/en/latest/api/trace.html#opentelemetry.trace.TracerProvider.get_tracer) state:

> The uniquely identifiable name for instrumentation scope, such as instrumentation library, package, module or class name. `__name__` may not be used as this can result in different tracer names if the tracers are in different files. It is better to use a fixed string that can be imported where needed and used consistently as the name of the tracer.

However, in many places in the docs, `__name__` is used for this.

**What is the name + path of the page that needs changed?**

https://opentelemetry.io/docs/instrumentation/python/cookbook/ and others

**Comment by srikanthccv** [comment]
It is fine to use `__name__`. There are many OTEL contrib instrumentation that uses `__name__` https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib+get_tracer%28__name__&type=code and examples/docs maintained on the core repo do the same https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python%20get_tracer(__name__&type=code. The `MAY` clause is used to let the reader know it may not always be the correct to use `__name__` for the scope.

**Comment by cartermp** [comment]
> as long as the user knows the scope differentiation

Hmm, that seems to me that maybe it shouldn't be what's documented then? Or it is documented, but called with this caveat?

**Comment by srikanthccv** [comment]
> The uniquely identifiable name for instrumentation scope, such as instrumentation library, package, module or class name.

Does this part of the `get_tracer` documentation make it any clear?

**Comment by WesleyAC** [comment]
Yeah, as a user I did a lot of reading docs and issues about this but still couldn't answer the question "what is this name actually used for" which is probably the most important think to know to be able to choose a useful one.

**Comment by srikanthccv** [comment]
>What should people name a tracer, taking the behavior that python has in place into consideration

>We need to be opinionated here. Saying it can be anything depending on what works for you isn't helpful

Following is the OTEL spec description for the instrumentation scope. 

_A logical unit of the application code with which the emitted telemetry can be associated. It is typically the developer’s choice to decide what denotes a reasonable instrumentation scope. The most common approach is to use the [instrumentation library](https://opentelemetry.io/docs/reference/specification/glossary/#instrumentation-library) as the scope, however other scopes are also common, e.g. a module, a package, or a class can be chosen as the instrumentation scope_

Python docs are based on the spec. I don't think there is anything specific about Python to add to what is already documented. The (Python) package name, module or class name are the most common & recommended choices, but ultimately it's up to the developer. We have refrained from making any opinionated changes for docs (the only exception to opinionated decisions was the implementation based on programming language idioms).

>as a user I did a lot of reading docs and issues about this but still couldn't answer the question "what is this name actually used for"

This is not specific to any language. OTEL has tons of concepts, which can be overwhelming, and there is not much about the instrumentation scope other than a glossary. Do you understand now what it is used for? If so, do you still think it is incorrectly used?
 
I would like to emphasize that choosing `__name__` is fine. It is a recommended option for module names. However, it should be noted that the phrase "**_`__name__` may not be used_**" has a MAY clause, following the short explanation for why it may not always be the right choice. We could probably highlight it. Either way, I wouldn't have made the changes.

**Comment by WesleyAC** [comment]
> Do you understand now what it is used for?

Maybe? I presume that it's possible to filter by it or something, but it's not clear to me that anyone actually does that. What it means is clear, but OTEL is so abstracted that the *use* is not really. But that problem seems endemic to OTEL, to the point where people maybe don't think it's a problem?

> However, it should be noted that the phrase "`__name__` **_may not be used_**" has a MAY clause, following the short explanation for why it may not always be the right choice.

This is not how the phrase "may not" is used in any dialect of English I'm familiar with. See, for instance [this English stack exchange post](https://english.stackexchange.com/questions/189974/why-do-they-say-may-not-for-things-which-people-shouldnt-do) for a explanation of this. And "MAY NOT" is not defined in RFC 2119 (unlike "MUST NOT" and "SHOULD NOT", for instance), so it's not like it's meaningful in that sense. If you think that `__name__` is fine to use (which it seems like in some circumstances it could be), the documentation should be changed, because "may not" does not mean what you seem to think it means.

**Comment by srikanthccv** [comment]
I could be wrong in the phrase/word usage since I am not a native English speaker. Any [documentation](https://github.com/open-telemetry/opentelemetry-python/blob/3732fd4a196555715e541cfa936ddf3c43ccd4ee/opentelemetry-api/src/opentelemetry/trace/__init__.py#L207) changes that make it clear are always welcome.

**Comment by cartermp** [comment]
It's still not clear from this nor your proposed changes @srikanthccv what the name should be.

The docstring you link says this:

> It is better to use a fixed string that can be imported where needed and used consistently as the name of the tracer.

To me, that means "don't use `__name__`. All the current docs are doing is reflecting that.

**Comment by srikanthccv** [comment]
I am sorry. I am not sure how to elaborate further than what I already mentioned.

**Comment by rernst76** [comment]
@srikanthccv Thank you for clarifying this issue! Your explanation is clear, and I understand that this is an implementation detail left up to the team managing the instrumentation. From the spec there is no prescriptive guidance on what can and cannot be used here, but the developers of any instrumenting library need to understand the tradeoffs of what to use for `instrumenting_module_name` to ensure a consistent and logical approach.

That being said, I do agree with @WesleyAC that the **language in the Python SDK and API docs is wrong** when considering your explanation.

Currently, it is written as

> The uniquely identifiable name for instrumentation scope, such as instrumentation library, package, module or class name. `__name__` may not be used as this can result in different tracer names if the tracers are in different files. It is better to use a fixed string that can be imported where needed and used consistently as the name of the tracer.

This should not be the name of the module that is instrumented but the name of the module doing the instrumentation. E.g., instead of "requests", use "opentelemetry.instrumentation.requests".

Based on my understanding of your explanation, the API and SDK docs should be much less prescriptive, something like:

> The uniquely identifiable name for instrumentation scope, such as instrumentation library, package, module, or class name.

As written now, the [Python Instrumentation Docs](https://opentelemetry.io/docs/languages/python/instrumentation/) are inconsistent with the [API](https://opentelemetry-python.readthedocs.io/en/latest/api/trace.html#opentelemetry.trace.TracerProvider) and [SDK](https://opentelemetry-python.readthedocs.io/en/latest/sdk/trace.html#opentelemetry.sdk.trace.TracerProvider) docs.

Revising the API and SDK docs to be less prescriptive, as I suggest above, would provide consistency in the documentation.

@srikanthccv Is this a change you would support? I would be happy to make a PR for this.

**Comment by srikanthccv** [comment]
Hi @rernst76, I am no longer part of the Python maintainers team. You might want to create an issue here https://github.com/open-telemetry/opentelemetry-python and discuss it.
