### ISSUE TITLE
Instrumentation: JS: Consider Placing the registerInstrumentations Call after the provider.register Call

### ISSUE THREAD

**Issue by Grunet** [open-telemetry/opentelemetry.io#2596]
I was working from https://opentelemetry.io/docs/instrumentation/js/instrumentation/ specifically

In investigating https://github.com/open-telemetry/opentelemetry-js/issues/3719 , [I noticed](https://github.com/open-telemetry/opentelemetry-js/issues/3719#issuecomment-1502661920) that doing this consistently closed a 4-5ms gap between the start of the trace and the start of the 1st child span.

I have no idea why this would matter at all, but it does seem to have made a difference for the example I was trying out so I wanted to bring it up in case it made sense.

(And if it matters I'm sensitive in general to milliseconds because Deno Deploy and other edge function services limit execution to 10s of ms of CPU time)

**Comment by cartermp** [comment]
...huh. I'd be curious how your experience is if you use the Node SDK? Or is that not applicable on Deno? (sorry, never used Deno)

The NodeSDK is what people tend to use more and it's what I'm planning on moving to docs to eventually. It places `registerInstrumentations` before registering the tracer provider: https://github.com/open-telemetry/opentelemetry-js/blob/053acb604c9d2b735bb267ff47724bb3af1ffd62/experimental/packages/opentelemetry-sdk-node/src/sdk.ts#L235

**Comment by Grunet** [comment]
[I tried the Node SDK just now with this code](https://github.com/Grunet/otel-js-deno-experimentation/blob/use-node-sdk/index.ts) and am seeing similar results. Here's an example:

![3 long horizontal bars each above one another vertically on the page. The 2nd bar starts a little after the 1st bar, and per the axis is roughly 4 milliseconds delayed](https://user-images.githubusercontent.com/29322882/232945727-95bb7723-6184-4be8-ad11-8766704d3808.png)

Does it matter that this is the first request to the server by chance?

**Comment by cartermp** [comment]
wow, holy shit, that's super weird. I wouldn't have any clue as to why that's happening. I'm not sure if we should change our docs just yet, since this smells like an upstream SDK problem here.

**Comment by Grunet** [comment]
Ok no worries I'll go ahead and close this and follow up in otel-js

**Comment by dyladan** [comment]
@Grunet I suspect what you're experiencing is latency added by the proxy tracer provider in the API. If you acquire a tracer before registering the TracerProvider you receive a `ProxyTracer ` object which no-ops by default. If you then register a real `TracerProvider`, the `ProxyTracer` will proxy calls to the real `Tracer` returned by the `TracerProvider`. The advantage of this is that any instrumentation which acquires a `Tracer` before your SDK is loaded will become active after the SDK is loaded. The disadvantage is that these early-loaded tracers will have a very slight performance penalty due to the proxy function overhead. Registering the provider before registering instrumentations avoids this overhead because the instrumentations get real tracers and you avoid the proxy.
