### ISSUE TITLE
Unclear description of Connectors on Configuration Page

### ISSUE THREAD

**Issue by gitmlynch** [open-telemetry/opentelemetry.io#2725]
The second sentence in the [`Connectors` section](https://opentelemetry.io/docs/collector/configuration/#connectors) reads;

> It consumes data as an exporter in one pipeline and emits data as a receiver in another pipeline.

Is this statement correct? If so I find the phrasing confusing. In normal language, I would associate a `receiver` with the activity of consumption and an `exporter` with the activity of emission. If the statement is indeed correct, would the following suggestion still be correct and more understandable?

"It consumes data from a processor as an exporter in one pipeline and emits data to a processor as a receiver in another pipeline."

**Comment by svrnm** [comment]
good call, I copied from [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/connector/README.md), so there are 2 places where we need to fix this.

cc @djaglowski 

@gitmlynch feel free to provide a PR and we can take it in

**Comment by gitmlynch** [comment]
Oh, before I do I PR, I need clarification. Is the statement currently correct and will benefit from enhanced phrasing, or is it incorrect atm?

**Comment by cartermp** [comment]
The statement is currently correct, but could benefit from better phrasing, yes.

**Comment by djaglowski** [comment]
> It consumes data as an exporter in one pipeline and emits data as a receiver in another pipeline.

This statement is correct with regard to the fact that a connector consumes data as an exporter and emits it as a receiver. It is technically incorrect in a different sense - a more accurate description would be, "It consumes data as an exporter in **one or more pipelines** and emits data as a receiver in **one or more other pipelines**" (I omitted this nuance because I thought it an unnecessary detail for those first trying to understand connectors.)

> It consumes data from a processor as an exporter in one pipeline and emits data to a processor as a receiver in another pipeline.

This is incorrect in the same way as described above (in that it may _consume from_ one or more processors and _emit to_ one or more processors). More importantly, it is inaccurate because pipelines do not necessarily contain processors at all, so the data consumed by a connector may be emitted directly from processors, receivers, or connectors. Likewise, the data emitted by a connector may be consumed directly by processors, exporters, or connectors.

Generally, I think we should not describe connectors based on their relationship to adjacent components because there are too many possible permutations. It's better in my opinion to describe connectors based on their dual roles as an exporter and receiver.

> In normal language, I would associate a receiver with the activity of consumption and an exporter with the activity of emission.

This is good feedback. It's natural to think about receivers and exporters in terms of their external-facing roles. However, if you include the behavior of components _within_ a pipeline, it is accurate to say that all pipeline components both consume and emit data. In my opinion, it's difficult to describe connectors accurately unless this is taken into account.

I'm not immediately finding a concise way to clarify the language but I'll continue to think on this and would appreciate additional suggestions.

**Comment by gitmlynch** [comment]
Thanks for the feedback. I will also give it more thought and try to offer a better suggestion for improvement.

**Comment by djaglowski** [comment]
> As the name suggests a Connector connects two pipelines: It consumes data as an exporter at the end of one pipeline and emits data as a receiver at the front of another pipeline.

This sounds clear to me. I've opened https://github.com/open-telemetry/opentelemetry.io/pull/2776 and https://github.com/open-telemetry/opentelemetry-collector/pull/7715 to incorporate this.

**Comment by cartermp** [comment]
This should be addressed now that the PR is merged. Thanks @djaglowski!
