### ISSUE TITLE
Lambda Collector Configuration

### ISSUE THREAD

**Issue by klempinen** [open-telemetry/opentelemetry.io#2800]
Page seems to be missing table of ARNs referred

**Comment by pranavmarla** [comment]
Agreed, both the [lambda collector config doc](https://opentelemetry.io/docs/faas/lambda-collector/) as well as the [lambda auto-instrumentation doc](https://opentelemetry.io/docs/faas/lambda-auto-instrument/) tell the user to copy the ARN of the desired lambda layer, but the ARNs are not actually provided anywhere.
As far as I can tell this means that, as of now, since it's missing such key information, this documentation is basically unusable.

**Comment by klempinen** [comment]
@svrnm Confirmed, closing issue.
