### ISSUE TITLE
Schema files should now be served from the Semantic Conventions repository

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry.io#2907]
Right now Hugo / OpenTelemetry.io is serving schema files from the local checkout of the specification.

See: https://github.com/open-telemetry/opentelemetry.io/blob/main/hugo.yaml#L194C14-L194C14

Instead, this should be pulled from this location: https://github.com/open-telemetry/semantic-conventions/tree/main/schemas

**Comment by chalin** [comment]
@jsuereth - in https://github.com/open-telemetry/opentelemetry.io/pull/2908#issue-1775297206 you wrote:

> DO NOT MERGE: This would make the 1.21.0 schema available immediately.

But 1.21.0 is _already_ available via https://opentelemetry.io/schemas/1.21.0 since the OTel spec is officially at 1.22.0. Is there something I'm missing?

Oh! I just checked, and apparently there is a difference between the OTel and semconv 1.21.0 schedmas:

```diff
diff --git a/schemas/1.21.0 b/schemas/1.21.0
index 7831021ee..f458225c5 100644
--- a/schemas/1.21.0
+++ b/schemas/1.21.0
@@ -44,7 +44,12 @@ versions:
               http.scheme: url.scheme
               http.url: url.full
               http.request_content_length: http.request.body.size
-              http.response_content_length: http.response.body.size  
+              http.response_content_length: http.response.body.size
+    metrics:
+      changes:
+        # https://github.com/open-telemetry/semantic-conventions/pull/53
+        - rename_metrics:
+            process.runtime.jvm.cpu.utilization: process.runtime.jvm.cpu.recent_utilization
   1.20.0:
     spans:
       changes:
```

I didn't know that schema files could be updated once they were published.

/cc @joaopgrassi
