### ISSUE TITLE
Add a "How to Contribute" section to opentelemetry.io

### ISSUE THREAD

**Issue by avillela** [open-telemetry/opentelemetry.io#3254]
**Desired feature or idea**: There's a lot of information in the OTel repos explaining how to contribute to different areas of OpenTelemetry; however, we don't have a centralized location to document this. Adding a "contributing" tab off of opentelemetry.io could serve as a "one stop shop" for folks who want to know of the different ways in which they can contribute to the project.

**Additional context**: After speaking with @svrnm, he suggested that I [create a blog post on the OTel blog](https://github.com/open-telemetry/opentelemetry.io/pull/3238) based on [this Medium article](https://medium.com/cloud-native-daily/how-to-contribute-to-opentelemetry-5962e8b2447e) that I published recently, as a stop-gap, until we can put together a such a page.

**Comment by svrnm** [comment]
Not sure if there should be a dedicated "Contributing" tab, or if this should live under "Community", as we have a simple version of that already there: https://opentelemetry.io/community/#develop-and-contribute, but I overall agree that it would be great to have that "one stop shop"

I think there are a few things we need to distinguish:
* The "rules" to contribute, which are contained in the CONTRIBUTING.md of each project, by rules I mean things like "use npm this and that way" or "your commits should have this and that structure"
* The "formal" set of things how you can be part of the community, which live at https://github.com/open-telemetry/community/
* Some "informal" recommendations (like your blog post), on how to get started with contributing, especially aimed towards new comers

I think we can add the most value by enriching the website with more of the "informal" stuff where we provide people with some soft suggestions on how they can get started. So that would be the point for me to begin with. 

As an additional reference, I'll leave https://www.kubernetes.dev/ here, as "_[t]his site is the home of contributor documentation, and serves as a starting point for your journey as a Kubernetes contributor._"

**Comment by chalin** [comment]
Hi all. Not sure if you consider this a duplicate or simply a related issue of the following issues, but I wanted to mention and cross-link them since this topic isn't new:

- #897
- #1890
