### ISSUE TITLE
Is there an index for all available schema?

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry.io#3256]
I am writing code that uses these schema and would like to create automation that checks all published schema are supported. To do this I need to be able to dynamically get a list of all published schema.

Ideally, I would be able to make a request to the opentelemetry.io website and get an index of all published schema and their URLs.

Does this already exist, or is it something that would need to be added?

**Comment by svrnm** [comment]
That's something that would need to be added. Question is, if this should be done via the opentelemetry website or if it should come from https://github.com/open-telemetry/semantic-conventions/, because as of today the schemas are loaded via a submodule from there 

Any suggestions, @chalin ?

**Comment by chalin** [comment]
Hi @MrAlias, I'm back from vacation now.

I'd like to better understand your needs and what you are trying to achieve. First a question ...

> would like to create automation that checks all published schema are supported

Wasn't there such a check in the OTel spec repo at one point? Is it that check that you are trying to rework?

**Comment by MrAlias** [comment]
I'm writing a translation utility for resource attributes based on OTel schema. My needs have changed slightly as it has been developed, and now I need to ensure that I have the latest schema published. It would be ideal if there was some query I can make to get the "latest" schema.

**Comment by svrnm** [comment]
@MrAlias would it help if `https://opentelemetry.io/schemas/latest` points to the latest schema via a redirect? So you hit that URL and it gives a 302 and a Location?

**Comment by MrAlias** [comment]
Yeah, that would be great!

**Comment by svrnm** [comment]
@chalin is this something we can do with hugo easily?

**Comment by chalin** [comment]
@open-telemetry/specs-semconv-maintainers @jsuereth: can we safely assume that the latest release of semconv (https://github.com/open-telemetry/semantic-conventions/releases/latest) for tag X.Y.Z can generally be assumed to mean that X.Y.Z is the latest schema? (I'm asking because, at some point in the recent past, we published schema 1.21.0 on the website when we shouldn't have.)

If so then yes, @svrnm and @MrAlias, I can add something to the auto-version update process to also create a redirect rule for https://opentelemetry.io/schemas/latest to be mapped to X.Y.Z, the latest semconv release.

Thoughts?

**Comment by chalin** [comment]
Actually, used another strategy, see:

- #3469, which defines `/schemas/latest` is a redirect
