### ISSUE TITLE
Explain rationale for `Status` attribute `Unset` vs `OK `

### ISSUE THREAD

**Issue by hterik** [open-telemetry/opentelemetry.io#3685]
**What needs to be changed?** 
I'm having a hard time understanding how the `Status` attribute is intended to be used.
`Error` vs not `Error` is rather obvious, but `Unset` vs `Ok` is very unclear.
Not only can `Unset` be misinterpreted as "span-still-in-progress", it appears like even completed spans can be in `unset` status.

*  https://opentelemetry.io/docs/instrumentation/python/manual/#set-span-status 
    This page says `don’t set StatusCode.OK on successfully-completed spans.` but it doesn't explain why? Why would a completed span not be OK? 
* https://opentelemetry.io/docs/concepts/signals/traces/#span-status says `By setting a Span status to Unset, the back-end that processes spans can now assign a final status.`.  This adds some justification but i'm still not understanding why the span receiver would change the status of what application has assigned.

Are there other pages giving a more complete picture of how this is intended to be used?

**Comment by svrnm** [comment]
In the case of unclarity always check with the spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status

`StatusCode` is one of the following values:

- `Unset`
  - The default status.
- `Ok`
  - The operation has been validated by an Application developer or Operator to
    have completed successfully.
- `Error`
  - The operation contains an error.

Indeed some of the language in the documentation needs to be updated, so thanks for flagging this

**Comment by hterik** [comment]
Thanks. The page above contains some more info. With pretty clear instructions to _how_ libraries should behave, but also lacking justification for _why_.
Thinking mostly about this section:

> **Generally, Instrumentation Libraries SHOULD NOT set the status code to Ok**, unless explicitly configured to do so. **Instrumentation Libraries SHOULD leave the status code as Unset** unless there is an error, as described above.
> 
> Application developers and Operators may set the status code to Ok.

The reason i'm bringing this up is because we've been using the standard context-managers to record spans and it is very surprising that they leave the status as unset after being exited successfully.
```py
with tracer.start_as_current_span("test") as span:
    pass
print(span.status)  # Remains unset, even after flush. Expected according to spec? Surprising IMO.
```
Explicitly marking every completed span as ok would give very verbose code and will be easy to forget. If nobody does this, downstream consumers can only assume that unset is equal to ok.

**Comment by svrnm** [comment]
Who is "we"? Are you developing a library or an application? The _why_ may be a little bit opaque, but from how I see it the idea is that it is upon application developers / operators (=those who have contextual knowledge about the application) are the only ones who can properly decide if a span is "OK" especially after it was set to "Error" initially, but might be recovered from that. So "Unset" means "nothing to worry about", Error means "something went wrong" with a mandatory description telling you what went wrong, and OK means we took a closer look and this OK (maybe even after the span status has been set to Error before, but it was treated properly).

This is how _I_ read it (I might be wrong!), so I suggest that you raise an issue with https://github.com/open-telemetry/opentelemetry-specification/ calling out that it is not clear _why_ things are that way and people may add additional details (e.g. via examples)

cc @open-telemetry/specs-approvers

**Comment by svrnm** [comment]
For additional details, see https://github.com/open-telemetry/oteps/blob/main/text/trace/0136-error_flagging.md

**Comment by cartermp** [comment]
Another consideration is that there may be downstream tools that process data and set the status based on some rule or condition. IMO it's best to not assume at the app/service level that everything is actually OK.

The other way I've thought about it is Unset means "default to OK if nobody down the chain says otherwise". And I believe most backends will treat it as such.

**Comment by hterik** [comment]
Ok, so to take i step back i will explain how i ended up in this situation.

As an application developer, i found a piece of code in our code base that under some conditions is running slowly, it looks like this:

```py
with tracer.start_as_current_span("do_stuff"):
    do_stuff()
```
To understand why it is running slowly and how frequently it happens, i open up Grafana Tempo to search for all occurrences of slow `do_stuff`s, I'm only interested in the cases where it ran to completion, not if it threw exception. Grafana presents me with this UI:
![image](https://github.com/open-telemetry/opentelemetry.io/assets/89977373/a82333f7-ec13-49c7-b439-437ed755659d)

As a dumb application developer, who hasn't studied the intricacies of the opentelemetry spec. My interpretation of these values can only be: (**I now realize that this interpretation is wrong**.)

> * **Unset** =  :face_with_spiral_eyes: :face_with_spiral_eyes: :raised_eyebrow: Maybe not completed yet? "_Probably not something important_"
> * **Error** = Error
> * **Ok** = `do_stuff()` ran to completion without any errors

One could claim this is a UX issue with Grafana, but after reading the [OpenTelemetry documentation about spans](https://opentelemetry.io/docs/concepts/signals/traces/#span-status), it doesn't use a single word to explain what OK means. I am non the wiser.

After realizing i'm not finding any spans when searching for status=ok. I start digging in the opentelemetry code to see if the `start_as_current_span` has a bug. After a while i reach the spec where it says that instrumentation libraries shouldn't set ok, instead something only application developers do.  This gives me interpretation 2:

> * **Unset** = Completed without error
> * **Error** = Error
> * **Ok** = Ok, despite what any instrumentation library might think.

(It's still not entirely clear why the library can't set OK when `start_as_current_span` completes, because in my books,  `start_as_current_span`  is something you typically run in application context. It's not auto-instrumentation we are using here. This is OT to the documentation though)

Reading through the justification in the otep further, it seems like OK should almost exclusively be used to silence known errors. Giving third interpretation

> * **Unset** = Completed without error
> * **Error** = Error
> * **Ok** = Known error, can be ignored.

This may also be a bit wrong, since you are allowed to set OK pro-actively, even if it is not a known error.

Personally, i think i understand the use and purposes now, the solution to my original problem is simple, just search for `status!=error`. But i have to say that it is very difficult to reach this conclusion and the documentation around this could benefit from some clarifications.

**Comment by svrnm** [comment]
> Personally, i think i understand the use and purposes now, the solution to my original problem is simple, just search for status!=error. But i have to say that it is very difficult to reach this conclusion and the documentation around this could benefit from some clarifications.

I agree with you on that. After reading the reasoning about it, it totally makes sense, but where it is explained on the website there is space to improve.

This is my interpretation now, but I think you could set the status to OK at the end of do_stuff if (and only if) do_stuff is part of your application and not part of a library: the do not set OK is for **library** developers, and this has a good reason, as they can not judge if something is "OK" for real. here's an example: 

* a HTTP client library calls a service, they get back a 200 status so they set the Span Status to OK, but the app developer looks into the response and it's some custom error not (properly) transported via http status code, so the span needs to be set to error, which by then is not possible anymore. 
* a HTTP client library calls a service, they get back a 400 status so they set the Span Status to Error (correctly), but the app developer expected an Error because they submitted a malformed request intentionally (for whatever reason, testing?), so they can set the Span Status to OK (but keep the http status code to 400), which will even tell the observability backend eventually to IGNORE this error in any kind of error reporting.

**Comment by cartermp** [comment]
@hterik this is a good walkthrough of your experience here. I think we can and should clarify it in the docs. Should be a relatively simple fix.

I think we should clarify that a primary use case for setting the span status yourself is to override with OK (like in the example @svrnm gives). In my experience, most people do not set a status explicitly and that's largely by design. We just don't clarify that at all here.

**Comment by yurishkuro** [comment]
I think the OP's point is the spec's decision is just a bad one. It optimizes for a subset of scenarios, but ignores another large set where instrumentation absolutely knows that a span was OK, as in case of inner spans. 

Yes, at least explaining this in the docs is a must, but doesn't address the usability problem.

**Comment by cartermp** [comment]
I took a stab at it here: https://github.com/open-telemetry/opentelemetry.io/pull/3694

**Comment by adriangb** [comment]
Having spent a lot of time with opentelemetry (I work for a startup that builds a hosted backend) I still do not understand the rational for this decision nor have I ever myself set or seen any of our users set the status code themselves. In fact running a `count(*)` on several days of data from multiple clients I don't see a _single_ use of `OK` amongst hundreds of million spans.

I believe there are two parts to the problem:
- It's not clear to users what the benefit is to them of setting this or why they would do that. Nothing ever prompts them to do it.
- If it requires manual work, users won't do it. E.g. using a context manager to catch exceptions and record them is very cheap.

IMO it would have been a better use of the bytes over the wire to just have a boolean or set it to OK on successful completion of the span without exceptions.

**Comment by yurishkuro** [comment]
My suggestion is to require Tracer to convert Unset to OK just before exporting the span. The Unset state is only useful while the span is active.

**Comment by svrnm** [comment]
@adriangb @yurishkuro I assume this is a discussion that needs to happen at the spec repo?

**Comment by yurishkuro** [comment]
Yes, but I don't have time to champion it. It's also strictly speaking not necessary, the current spec already says that unset is effectively the same as OK unless someone overrides it. Once the span is exported, there's no someone who can override it, so I could argue that if @adriangb is having problem with usability of captured traces he should raise the issue with his vendor - the vendor is perfectly free to override unset->ok on ingestion, no spec changes required. In case of Jaeger this happens automatically because we defined the transformation rule `jaegerSpan.tag[error] = true iff otelSpan.status == ERROR`
