### ISSUE TITLE
Instrumentation for kotlin

### ISSUE THREAD

**Issue by Roshan8375** [open-telemetry/opentelemetry.io#3718]
i am trying to instrument react-native android part.
there is no documentation about instrumentation of kotlin in here but there in opentelemetry registry it has kotlin language.
please include for kotlin aswell.

**Comment by svrnm** [comment]
Hi @Roshan8375, 

thank you for raising this issue. I am not a kotlin expert, but from what you describe, you might like to take a look at https://github.com/open-telemetry/opentelemetry-android, it's a fairly new project, that's why there is no documentation yet. (cc @open-telemetry/android-approvers)

For having a section on kotlin in general, I have to refer to @open-telemetry/javascript-approvers , if this is something we should add?

**Comment by LikeTheSalad** [comment]
Hi @Roshan8375 

We're currently working on this new Otel Android project https://github.com/open-telemetry/opentelemetry-android as mentioned by @svrnm where we're adding built-in support for common Android apps use cases that need telemetry. However, the base of the OTel Android lib is the [OTel Java SDK](https://github.com/open-telemetry/opentelemetry-java) which works well for Android projects too, and can be used from Kotlin code as well thanks to Kotlin's great interoperability support for Java.

There is a Kotlin-specific OTel library right now which is this one: https://github.com/open-telemetry/opentelemetry-java/tree/main/extensions/kotlin though it's not a full-Kotlin SDK but rather an extension for the Java SDK to help with instrumentations that need to run in Kotlin coroutines in order to preserve OTel's Contexts across any coroutine-context changes. You can take a look at [this example](https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/kotlin-extension) to check more details on how to use this Kotlin extension.

**Comment by Roshan8375** [comment]
thanks for help
as React-native have android and ios both i had to instrument both separately so instead of that i did something with js for http instrumentation it is working for both now.
