### ISSUE TITLE
Confusing documentation on building a custom connector

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/opentelemetry.io#4071]
The [Building a custom collector](https://opentelemetry.io/docs/collector/custom-collector) page starts by explaining how to install the builder, which is required to turn the custom collector's yaml config into an actual component.

The paragraph instructs to download the binary from the [opentelemetry-collector releases page](https://github.com/open-telemetry/opentelemetry-collector/releases).
However, this page is a bit confusing, as releases don't only include the builder, only the latest release's assets are expanded and that may not be the builder.
This page also has a big `Images and binaries here:` pointing to another repository's release page, which isn't for the builder.

This documentation should be made clearer, so folks who want to build their own distribution of the collector can more easily figure out how to get the builder.

See also this slack discussion: https://cloud-native.slack.com/archives/C01N6P7KR6W/p1709195136597799

**Comment by svrnm** [comment]
Note, the challenge until recently was that pointing to https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.95.0 was difficult due to the changing version number, but we can fix this now with a little trick we also use for the rust documentation:

```
https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2F{{% version-from-registry exporter-rust-stdout %}}
```

We need to add the `package` info to `data/registry/collector-builder.yml` similar to what we have for other go based components and then it will be auto updated whenever there is a release.

**Comment by svrnm** [comment]
@dmathieu can you check if #4078 fixes your issue?

**Comment by dmathieu** [comment]
This is indeed much better, thank you!

**Comment by cartermp** [comment]
I'll close this out, but @dmathieu if you feel it should be re-opened for a specific purpose, ping here and I'll re-open.
