### ISSUE TITLE
Add GitHub Star counter to Website

### ISSUE THREAD

**Issue by lavishpal** [open-telemetry/opentelemetry.io#4254]
**Is your feature request related to a problem? Please describe.**
A lot of open source projects (e.g. [keptn](https://keptn.sh/stable/) have an interactive widget on the top right corner to display the up to the GitHub Star count (as well as the amount of forks and the latest release). 

**Describe the solution you'd like**
Add an interactive star counter that links to GitHub.

**Additional context**
 
![Screenshot (243)](https://github.com/open-telemetry/opentelemetry-collector/assets/128935617/28fc144f-1b3b-4dde-984b-9b1bc1f6559a)

**Comment by theletterf** [comment]
+CC @chalin

**Comment by svrnm** [comment]
@lavishpal from which project would you like to see the star? OpenTelemetry has multiple repositories so we can not point to that one repo and pick those stars. We can have the stars of sub projects on their specific pages

**Comment by chalin** [comment]
Hey @lavishpal - thanks for the suggestion. Here are my thoughts: the project has a lot on its plate and we are stretched thin already. I see little added value in spending cycles on this, esp. given the comment that @svrnm made (which of the many repos' stars would we want to consider etc.)

Our CNCF sister-project website ([kubernetes.io](https://kubernetes.io/)) doesn't have stars, and I'm quite ok for OTel's website to not have GH stars either. The website has a link to the GH repo, and they can see the stars there if they'd like.

This minor feature enhancement _may_ be worth considering at a later date, but for now (since we're making a clean up pass of the issues), I'd vote to close this. My 2 cents.

**Comment by svrnm** [comment]
+1 to what @chalin said, I would have no issues with listing those github stars eventually, but right now it's a fairly complicated question with an uncertain outcome. We might consider adding github stars or similar "ratings" to the registry, eventually but that's a different concern. @lavishpal if you have a concrete idea how this could be implemented (and the willingness to create the PR for it), raise a new issue and I am happy to discuss, but I will close this issue for now.

**Comment by lavishpal** [comment]
Couldn't agree more with  @chalin
