### ISSUE TITLE
Use "experimental" instead of "Experimental"

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry.io#4488]
Notice that `Experimental` (starting with capital letter) is used in Specification and Semantic Conventions. Can we have a separate issue so that we apply the trach and change in all possible places?

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry.io/pull/4463#discussion_r1601674734_

**Comment by pellared** [comment]
@chalin, @svrnm: Please feel free to edit my description.

**Comment by chalin** [comment]
Thanks for creating this issue to track the discussion. My main objective in the original edit was to ensure that "Collector" was capitalized. Otherwise, we (should) use sentence case in headings (per our language guide(ance) -- though we haven't started applying that consistently at all.

I like what @svrnm proposes.

All-in-all, this isn't a super important; and sorry for having brought it up. As I mentioned, it was really the capitalization of Collector I was primarily targeting.

**Comment by svrnm** [comment]
the way it is solved now and especially moving the "experimental" out of the title is a good solution! I think we can close this one
