### ISSUE TITLE
Create an exporter configuration guide for Prometheus

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry.io#45]
We need a guide on how to set up Prometheus in order to see metric data from OpenTelemetry. This can be similar to the Jaeger one, just a quick start for running it locally at first.

**Comment by Bhargavamacha** [comment]
Can I take this up?

**Comment by austinlparker** [comment]
Go for it.

**Comment by austinlparker** [comment]
This is being closed as each language will have its own exporter configuration guide.

**Comment by StevenACoffman** [comment]
Uh, Prometheus is not a programming language? How to set up Prometheus in order to collect the metric data from a OpenTelemetry exporter is a different thing. 
Are you suggesting that for every programming language you will export to the Prometheus Push Gateway? 
Are you suggesting that for every programming language you will demonstrate how to adapt OpenTelemetry monitoring to provide a Prometheus metric scrape endpoint?

I'm unclear as to why this is closed.

**Comment by austinlparker** [comment]
Since metrics are still in-flight for so many languages (and is officially unstable), we're going to defer website documentation on prometheus export to each SIGs github repo. Once the metrics API is more stable, then we'll come back around to adding some high-level docs on the website.
