### ISSUE TITLE
New Blog Post: Java Metric Systems Compared

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry.io#4517]
Saw the [contribution guide](https://opentelemetry.io/docs/contributing/blog/) for blog posts after I opened the PR #4512. Opening an issue to follow the guidelines.

- Title: Java Metric Systems Compared
- Description: A performance comparison of opentelemetry-java versus other popular java metrics systems. Includes a metrics primer, a breakdown of what all metric systems strive to do, and interesting implementation notes about opentelemetry-java's metrics SDK. Code for the performance comparison is checked into github in a personal repo.
- Technologies: opentelemetry-java, micrometer, prometheus, jmh (for benchmarking), and OTLP
- Name of related SIG: Java SIG
- Name of sponsor: Myself (@jack-berg). The content has also already been reviewed by the other opentelemetry-java maintainer, @jkwatson.

**Comment by svrnm** [comment]
Thanks for following the process, @jack-berg! Since the blog post comes out of the Java SIG there is no concern from my site to have it. I added @open-telemetry/java-approvers as reviewers to the blog post (although @trask already looked into it) and one of us (@open-telemetry/docs-approvers) will take a look eventually as well.
