### ISSUE TITLE
New Blog Post: 3 Things I Love About OpenTelemetry (and 3 Things I'd Like to Improve)

### ISSUE THREAD

**Issue by dmitchsplunk** [open-telemetry/opentelemetry.io#4837]
### Outline of Blog Post

I’ve had the opportunity to work closely with OpenTelemetry for the past several years.  During this time, I’ve worked with more than a hundred organizations of all sizes. 

Reflecting on this experience, the proposed blog post will share the top three things that I love about OpenTelemetry, as well as three things that I’d like to improve. 

Three things I love about OpenTelemetry: 

1. It’s Easy to Use! 
2. Flexibility of the OpenTelemetry Collector Architecture
3. Support for Logs

Three things I’d like to improve: 

1. Make OpenTelemetry Even Easier
2. Narrow the Gap with Traditional APM Agents
3. Expand Scope to Network and Security Domains 

Note: the post will be vendor-neutral, and won't mention any vendor-specific implementations of OpenTelemetry. 

### List of Technologies Used

- OpenTelemetry
- Kubernetes

### Related SIG

End-User SIG

### Name of Sponsor

@svrnm  

Note:  Severin and I both work for Cisco, so I expect we'll need another approver to review as well.

**Comment by svrnm** [comment]
@open-telemetry/sig-end-user-approvers please take a look!

**Comment by avillela** [comment]
I love this! Also, @dmitchsplunk I think it would be AMAZING if the End User SIG could have you do a live session version of this as well. Would you be up for it?

**Comment by dmitchsplunk** [comment]
Thanks @avillela, I love the idea of a live session!

**Comment by svrnm** [comment]
As @dmitchsplunk stated he and I are working at the same company. I also had the opportunity to read the version of this blog and it is a really amazing read, very balanced and very good in calling out the things he likes and thinks he sees to need improvement. So **personally** I am keen to see this blog post published.

We talked about the same during the SIG Comms call on Monday, and agreed that there are some challenges to publish an opinion blog post on the official otel blog, i.e. we would need to figure out how to capture feedback to that blog post (slack, github dicussion, github issue, etc.) and we also need to be aware that we might invite other blog posts that express an opinion about our project to be requested to be published, so we need to be clear on the rules to have those, and to be fully transparent, during the meeting there was a tendency to not publish opinion pieces and add guidelines to the blog submission to not have them. This is not a binding decision, and we agreed to talk this through in this issue (@hughesjj , @tiffany76 , @lisahjung, please check if I gave that back correctly)

For me there are 2 potential outcomes:
1. We do not have opinion pieces on the blog post and add that to the guidelines. I will work with @dmitchsplunk to publish this on a cisco/splunk blog 
2. We find a way to manage those blogs and have them as a good addition to the community.

Personally I think we can accomplish (2) and there I close the loop with @avillela's comment: having the EndUser SIG owning and driving this, similar to blog posts like the End-User Q&A Series we had with [Iris](https://opentelemetry.io/blog/2023/end-user-q-and-a-03/), [Doug](https://opentelemetry.io/blog/2023/end-user-q-and-a-02/) and [J](https://opentelemetry.io/blog/2023/end-user-q-and-a-01/), we should be able to capture this, while not having evidence that opinion blog posts can "simply" be published on our blog, as they have to go through the End User SIG.

@open-telemetry/sig-end-user-approvers , @open-telemetry/docs-approvers WDYT?

**Comment by theletterf** [comment]
Oh, this is a tough one...

This saddens me, because I'm a wild blogger, but I think the OpenTelemetry blog should not host opinion pieces, especially if they've the potential of giving the impression that the OpenTelemetry roadmap might be neglecting some aspects (not saying it's the case of Derek's post). These kind of posts belong to external blogs for the simple reason that, once you open that Pandora's box, there's no easy demarcation line that helps you decide what's a proper opinion piece and what isn't. We'd end up spending too many hours on the blog. We don't want that, I think.

I've a different proposal: We can turn interesting discussions into some sort of Reader's Mail section, where users can express concerns or ask questions that SIG members answer. Why on the blog and not in GH issues or discussions? Just as a way of giving it a more polished shape and focus, as well as visibility.

**Comment by tiffany76** [comment]
> (..., @tiffany76 , ..., please check if I gave that back correctly)

Your summary of the SIG meeting discussion looks good to me, @svrnm.

**Comment by musingvirtual** [comment]
If @dmitchsplunk is at as his name says the Splunk division of Cisco, I'm curious why the label end user applies here as they are an OpenTelemetry vendor?

In any case, I'm not sure that running all opinions through end user makes any sense as a proposal unless we are only taking opinions from end users - which might be a reasonable position to take in order to avoid having to work out whether the opinion of an employee of a vendor is their own opinion or the stance of that vendor.

I am generally not for the official blog taking opinions at all unless we create a very separate way to mark those.  I am sure that @dmitchsplunk means well, understands vendor-neutrality, and is likely stating his own opinion, and he's been very transparent about where he works.  However, I can see lots of possibilities for a particular vendor's commercial opinion to creep in that we might not be able to identify including vendors getting their customers to submit blogs that are partly ghostwritten, authors we don't realize work for vendors using personal GitHub emails, etc.

**Comment by cartermp** [comment]
I's be curious about what the contents are. In general I think it'd be a healthy thing if we're welcoming of end-user opinion pieces provided they're constructive in their criticisms and balanced in their praise.

**Comment by austinlparker** [comment]
I don't believe editorial content is really appropriate for the official project blog.

**Comment by avillela** [comment]
@dmitchsplunk we chatted internally at the End User SIG meeting today and in the interest of vendor neutrality, and the general consensus is that we’d love to hear instead directly from end-users if possible. I’m sure with your involvement with end users we can find interesting user stories that exemplify your experience.

**Comment by dmitchsplunk** [comment]
Hi @avillela - I understand.  Thanks to you and the End User SIG for your consideration.
