### ISSUE TITLE
Documentation for manual instrumentation with the Java SDK 

### ISSUE THREAD

**Issue by dmitchsplunk** [open-telemetry/opentelemetry.io#5735]
**What needs to be changed?** 

I'm looking for the steps required to initialize and use the Java OpenTelemetry SDK within an environment where it's not possible to utilize the otel-javaagent.jar agent. 

The older docs outlined this on the [instrumentation page](https://github.com/open-telemetry/opentelemetry.io/blob/aa67a243431901aaf1dc4cd920db43f163e67651/content/en/docs/languages/java/instrumentation.md). 

But I can't find an equivalent example in the [latest docs](https://opentelemetry.io/docs/languages/java/), as the Getting Started examples seem to assume that the otel-javaagent.jar file will be used, which isn't possible in all situations. 

**What is the name + path of the page that needs changed?** Perhaps the manual instrumentation steps for Java could be added here?  

https://opentelemetry.io/docs/languages/java/instrumentation/#manual-instrumentation

**Comment by tiffany76** [comment]
@open-telemetry/java-instrumentation-approvers, PTAL.

**Comment by breedx-splk** [comment]
Hey @dmitchsplunk. There's been considerable effort in the last couple months to reorg and improve the docs for java. It's very much intentional that the javaagent is prominent, because that's what the vast majority of users will use. I hope you can also appreciate that it was kinda stilly to have sdk documentation on a page about "instrumentation"....they're different things! The title of your issue and the description also appear to be conflating two concepts -- creation/configuration of the sdk and manual instrumentation. Manual instrumentation does require the sdk to be configured, but it's a separate thing. Also, there isn't just one singular way to do manual instrumentation....sometimes it's with tracing and creation of spans, sometimes it's generating metrics, etc.

Documentation on manually creating and configuring the sdk is described in https://opentelemetry.io/docs/languages/java/sdk/. There's a code snippet partway down the page that shows how to do it with programmatic configuration.

If you need to do additional configuration of the sdk, the details are in https://opentelemetry.io/docs/languages/java/configuration/. We expect most users to leverage autoconfiguration of the sdk (via env vars and system properties) to make things easier (less code).

And then finally there's documentation on how to use the API to generate telemetry (manual instrumentation): https://opentelemetry.io/docs/languages/java/api/. [See this section](https://opentelemetry.io/docs/languages/java/api/#span) for specifics.

Hopefully that helps. If you're content with this, please close...and if not, provide additional feedback. Thanks!

**Comment by dmitchsplunk** [comment]
Hi @breedx-splk , thanks for the detailed explanation, that helps me to understand where to find what I was looking for in the new docs structure. I'm good to close this.
