### ISSUE TITLE
On /status page, need to update Metrics SDK status from Experiment to feature-freeze

### ISSUE THREAD

**Issue by horovits** [open-telemetry/opentelemetry.io#874]
**What needs to be changed?**
On opentelemetry.io/status/ page, need to update SDK status from Experiment to feature-freeze

**What is the name + path of the page that needs changed?**
https://opentelemetry.io/status/
https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/status/_index.md

**Additional context**
to align with the achieved milestone

**Comment by chalin** [comment]
@tedsuo - can you comment?

**Comment by austinlparker** [comment]
SDK status for which component?

**Comment by horovits** [comment]
@austinlparker status for the metrics SDK specification

**Comment by chalin** [comment]
Actually, this isn't a bug since the website docs reflect the latest officially published specification version, which is https://github.com/open-telemetry/opentelemetry-specification/tree/v1.7.0 as of the time of writing.

https://github.com/open-telemetry/opentelemetry-specification/blob/v1.7.0/specification/metrics/sdk.md shows a status of experimental. So this is blocked until the next release of the specification.

@tedsuo - comments?
