### ISSUE TITLE
Can we have an official documentation for how to use this with Angular Applications

### ISSUE THREAD

**Issue by umarkhan17** [open-telemetry/opentelemetry.io#953]
I need to implement this in Angular application. Is there any documentation. Please assist.

**Comment by cartermp** [comment]
I'll close this out for now since we're, frankly, a very long way away from being able to offer docs and guidance for modern frontend instrumentation. This is something that is being designed as a core capability for OTel, and will likely involve a long period of experimentation as vendors also try to support it as a concept. So I don't think we can really offer anything helpful here until a whole bunch more work is done in OTel.
